// Ported from the user's Roblox-side "PNCCharges" Lua module (message.txt),
// keeping the same numeric IDs so arrest records referencing a charge ID
// (rather than a full name) can still be decoded to something readable.

export const PNC_CHARGES_BY_ID: Record<number, string> = {
  1: "Tampering with motor vehicles",
  2: "Leaving or operating a conveyance in a dangerous position",
  3: "Driving with an illegal modification",
  4: "Dangerous Driving",
  5: "Obstruction of the highway",
  6: "Driving whilst using a mobile telephone",
  7: "Failure to stop for a police constable",
  8: "Exceeding the speed limit",
  9: "Misuse of warning equipment",
  10: "Failure to stop after an accident",
  11: "Using a vehicle in a dangerous condition",
  12: "Motor racing on public ways",
  13: "Driving without due care or attention",
  14: "National Security Threat",
  15: "Tax Evasion",
  16: "MOD ACT",
  17: "Murder",
  18: "Murder x4",
  19: "Assault with intent to resist arrest",
  20: "Murder x3",
  21: "Battery",
  22: "Assault occasioning on actual bodily harm (ABH)",
  23: "False imprisonment",
  24: "Unlawful wounding and inflicting of grevous bodily harm (GBH)",
  25: "Murder x2",
  26: "Murder x5+",
  27: "Assault on emergency workers",
  28: "Accessory to an offence",
  29: "Causing the death of an emergency worker",
  30: "Deported",
  31: "Entry denied/Failure to comply",
  32: "Possession with Intent to Supply",
  33: "Simple Possession of a Controlled Substance",
  34: "Aggravated Possession of a Controlled Substance",
  35: "Equipped for production of substance ",
  36: "Supply of Controlled Substance",
  37: "Possession of an explosive",
  38: "Detonation of an explosive",
  39: "Animal Cruelty",
  40: "Criminal damage",
  41: "Aggravated tresspass",
  42: "Failure to company with a direction to leave land",
  43: "Theft",
  44: "Arson",
  45: "Trespass of a protected site",
  46: "Robbery",
  47: "Theft of a motor vehicle",
  48: "Taking a motor vehicle without consent",
  49: "Violent disorder",
  50: "Failure to identify",
  51: "Impersonation",
  52: "Provocation of violence",
  53: "Riot",
  54: "Obstructing and/or hindering emergency workers responding to emergency circumstances",
  55: "Harassment, alarm or distress",
  56: "Wasting of emergency services time",
  57: "Threats to kill",
  58: "Affray",
  59: "Discharge of an illegal firearm",
  60: "Brandishing a controlled weapon",
  61: "Use of a higher grade weapon",
  62: "Unlawful distribution of weapons",
  63: "Possession of an illegal firearm",
  64: "Possession of a higher grade weapon",
  65: "Possession of an offensive weapon",
  66: "Unlawful discharge of a controlled weapon",
  67: "Driving without a Valid License",
  68: "Forgery & Counterfeiting",
};

export function getChargeName(chargeId: number | string): string {
  const id = typeof chargeId === "string" ? parseInt(chargeId, 10) : chargeId;
  return PNC_CHARGES_BY_ID[id] || `Unknown charge (#${chargeId})`;
}
